name: deploy to Bucket

on:
  push:
    branches: [mongo]

jobs:
  deploy:
    name: Deploy to MONGO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [3.6, 4.0, 4.2]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.6.0
      with:
    # MongoDB version to use (default "latest")
        mongodb-version: # optional, default is latest
    # MongoDB replica set name (no replica set by default)
        mongodb-replica-set: # optional, default is 
    # MongoDB port to use (default 27017)
        mongodb-port: # optional, default is 27017